#!/usr/bin/env python3
"""Tests for change parsing, novelty detection, the AI summary and message assembly (standard library only)."""

import contextlib
import io
import json
import subprocess
import tempfile
import unittest
from pathlib import Path
from types import SimpleNamespace
from unittest import mock

import watch


def quiet():
    """Swallows the script's log lines so test output stays readable."""
    stack = contextlib.ExitStack()
    stack.enter_context(contextlib.redirect_stdout(io.StringIO()))
    stack.enter_context(contextlib.redirect_stderr(io.StringIO()))
    return stack


class TestFindEntry(unittest.TestCase):
    def test_top_keys_lookup(self):
        parsed = {"gpt-6-sol": {"input_cost_per_token": 2.5e-06, "max_input_tokens": 400000}}
        src = {"extract": "top_keys"}
        entry = watch.find_entry(parsed, src, "gpt-6-sol")
        self.assertEqual(entry["max_input_tokens"], 400000)

    def test_key_lookup_nested(self):
        parsed = {"data": [{"id": "claude-opus-5", "limit": {"context": 200000}}]}
        src = {"extract": "key", "key": "id"}
        entry = watch.find_entry(parsed, src, "claude-opus-5")
        self.assertEqual(entry["limit"]["context"], 200000)

    def test_missing_id_returns_none(self):
        src = {"extract": "key", "key": "id"}
        self.assertIsNone(watch.find_entry({"data": []}, src, "nope"))

    def test_text_source_has_no_parsed_json(self):
        self.assertIsNone(watch.find_entry(None, {"extract": "regex"}, "gpt-6-sol"))


class TestCodexFeed(unittest.TestCase):
    """The real feed-openai-codex entry from sources.json against lines like those the feed has carried."""

    def test_keeps_model_names_and_drops_crates(self):
        src = next(s for s in json.loads(watch.SOURCES.read_text(encoding="utf-8")) if s["name"] == "feed-openai-codex")
        atom = ("<title>Bump codex-rs to 0.51; add codex-imagegen-request-id header</title>"
                "<title>fix(codex-websocket-auth): retry</title><title>codex-minimal-sandbox cleanup</title>"
                "<content>Default to GPT-5.5 for new sessions; gpt-5.5 stays. Add gpt-6-sol.</content>"
                "<content>support gpt-image-2, o4-mini and codex-mini-latest; GPT-6</content>")
        _, ids, _ = watch.extract_ids(atom.encode("utf-8"), src)
        self.assertEqual(ids, ["codex-mini-latest", "gpt-5.5", "gpt-6", "gpt-6-sol", "gpt-image-2", "o4-mini"])

    def test_lowercase_is_opt_in(self):
        src = {"kind": "text", "extract": "regex", "pattern": r"(?i)\b(gpt-[\w.]+)"}
        self.assertEqual(watch.extract_ids(b"GPT-5.5 gpt-5.5", src)[1], ["GPT-5.5", "gpt-5.5"])
        self.assertEqual(watch.extract_ids(b"GPT-5.5 gpt-5.5", {**src, "lowercase": True})[1], ["gpt-5.5"])


class TestChatgptPlans(unittest.TestCase):
    """chatgpt-plans: the PlanType union the Codex client generates from its Rust enum of ChatGPT plans."""

    FILE = ("// GENERATED CODE! DO NOT MODIFY BY HAND!\n\n// This file was generated by [ts-rs]"
            "(https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.\n\nexport type PlanType = {};\n")

    def plan_type_ts(self, *plans):
        return self.FILE.format(" | ".join(f'"{p}"' for p in plans))

    def source(self):
        return next(s for s in json.loads(watch.SOURCES.read_text(encoding="utf-8")) if s["name"] == "chatgpt-plans")

    def test_reads_every_plan_and_nothing_else(self):
        text = self.plan_type_ts("free", "plus", "pro", "prolite", "edu_plus", "unknown")
        self.assertEqual(watch.extract_ids(text.encode("utf-8"), self.source())[1],
                         ["edu_plus", "free", "plus", "pro", "prolite", "unknown"])

    def test_a_new_plan_is_news(self):
        # 25.09.2026 00:20 UTC: promax, a tier above Pro, landed in Codex two hours after it surfaced in chatgpt.com
        with tempfile.TemporaryDirectory() as d:
            root = Path(d)
            (root / "data").mkdir()
            plans = root / "PlanType.ts"
            (root / "sources.json").write_text(json.dumps([{**self.source(), "url": plans.as_uri()}]), encoding="utf-8")

            def git(*args):
                subprocess.run(["git", "-c", "user.name=t", "-c", "user.email=t@t", *args], cwd=root, check=True,
                               capture_output=True)

            def check(*names):
                plans.write_text(self.plan_type_ts(*names), encoding="utf-8")
                with quiet(), mock.patch.object(watch, "ROOT", root), mock.patch.object(watch, "DATA", root / "data"), \
                        mock.patch.object(watch, "SOURCES", root / "sources.json"), \
                        mock.patch.object(watch, "send_telegram") as send, \
                        mock.patch.object(watch, "ai_summary", return_value="OpenAI готовит тариф Pro Max.") as ai:
                    watch.main([])
                git("add", "-A")
                git("commit", "-qm", "snapshot")
                return send, ai

            git("init", "-q")
            send, _ = check("free", "plus", "pro", "prolite")
            send.assert_not_called()  # a source's first snapshot is not news
            send, ai = check("free", "plus", "pro", "prolite", "promax")
            self.assertEqual([n["name"] for n in ai.call_args[0][0]["novel"]], ["promax"])
            self.assertIn("+ promax 🆕", send.call_args[0][0])


class TestAiPrompt(unittest.TestCase):
    def test_every_source_is_described_to_the_model(self):
        # the model reads source names in every payload; an undescribed one gets guessed at (a plan taken for a model)
        for src in json.loads(watch.SOURCES.read_text(encoding="utf-8")):
            with self.subTest(source=src["name"]):
                self.assertIn(src["name"], watch.AI_SYSTEM_PROMPT)


class TestKeyListExtract(unittest.TestCase):
    """extract=key_list: how apify sources hand over the strings the actor's page function matched."""

    def test_collects_strings_from_list_fields_anywhere_in_the_json(self):
        raw = json.dumps({"matches": ["gpt-6-sol", "GPT-5.5", 7],
                          "pages": [{"url": "https://chatgpt.com/", "matches": ["o4-mini", "gpt-6-sol"]}]})
        src = {"kind": "json", "extract": "key_list", "key": "matches"}
        self.assertEqual(watch.extract_ids(raw.encode("utf-8"), src)[1], ["7", "GPT-5.5", "gpt-6-sol", "o4-mini"])

    def test_requires_json(self):
        with self.assertRaises(ValueError):
            watch.extract_ids(b"plain text", {"kind": "text", "extract": "key_list", "key": "matches"})


class TestApify(unittest.TestCase):
    SRC = {"name": "chatgpt-web", "kind": "apify", "url": "https://chatgpt.com/", "token": "${APIFY_TOKEN}",
           "extract": "key_list", "key": "matches", "pattern": r"\b(gpt-[\w.\-]+)", "min_interval_hours": 6}
    NOW = "2026-09-25T12:00Z"

    def due(self, state=None, hours=6):
        with tempfile.TemporaryDirectory() as d:
            data = Path(d)
            if state is not None:
                (data / "chatgpt-web.apify-state.json").write_text(json.dumps(state), encoding="utf-8")
            with mock.patch.object(watch, "DATA", data):
                return watch.apify_due({**self.SRC, "min_interval_hours": hours}, at(self.NOW))

    def test_due_without_a_state_file(self):
        self.assertTrue(self.due())

    def test_not_due_right_after_a_run(self):
        self.assertFalse(self.due({"last_run": "2026-09-25T09:00Z"}))

    def test_due_once_the_interval_has_passed(self):
        self.assertTrue(self.due({"last_run": "2026-09-25T05:59Z"}))

    def test_a_broken_state_file_means_due(self):
        self.assertTrue(self.due({}))

    def test_run_builds_the_actor_call_and_packs_matches(self):
        items = [{"url": "https://chatgpt.com/", "scripts": 12, "fetched": 11, "blocked": 1,
                  "matches": ["gpt-6-sol", "GPT-5.5"]},
                 {"url": "https://chatgpt.com/", "scripts": 12, "fetched": 12, "blocked": 0,
                  "matches": ["o4-mini"]}]
        reply = mock.MagicMock()
        reply.__enter__.return_value.read.return_value = json.dumps(items).encode("utf-8")
        with mock.patch.object(watch.urllib.request, "urlopen", return_value=reply) as urlopen:
            raw = watch.apify_run(self.SRC, "apify-token")
        req = urlopen.call_args[0][0]
        self.assertTrue(req.full_url.startswith(
            "https://api.apify.com/v2/acts/apify~playwright-scraper/run-sync-get-dataset-items?"))
        self.assertIn("token=apify-token", req.full_url)
        body = json.loads(req.data.decode("utf-8"))
        self.assertEqual(body["startUrls"], [{"url": "https://chatgpt.com/"}])
        self.assertEqual(body["proxyConfiguration"]["apifyProxyGroups"], ["RESIDENTIAL"])
        self.assertIn(json.dumps(self.SRC["pattern"]), body["pageFunction"])  # the site's regex, JSON-escaped
        self.assertIn("'gi'", body["pageFunction"])
        snapshot = json.loads(raw.decode("utf-8"))
        self.assertEqual(snapshot["matches"], ["GPT-5.5", "gpt-6-sol", "o4-mini"])
        self.assertEqual(snapshot["pages"][0]["blocked"], 1)
        _, ids, _ = watch.extract_ids(raw, {**self.SRC, "lowercase": True})
        self.assertEqual(ids, ["gpt-5.5", "gpt-6-sol", "o4-mini"])

    def test_fetch_source_skips_without_a_token(self):
        with mock.patch.dict("os.environ", {}, clear=True), quiet():
            self.assertIsNone(watch.fetch_source(self.SRC, {}, at(self.NOW)))

    def test_fetch_source_skips_inside_the_interval(self):
        with tempfile.TemporaryDirectory() as d:
            (Path(d) / "chatgpt-web.apify-state.json").write_text('{"last_run": "2026-09-25T11:30Z"}\n',
                                                                  encoding="utf-8")
            with mock.patch.dict("os.environ", {"APIFY_TOKEN": "t"}, clear=True), \
                    mock.patch.object(watch, "DATA", Path(d)), quiet(), \
                    mock.patch.object(watch, "apify_run") as run:
                self.assertIsNone(watch.fetch_source(self.SRC, {}, at(self.NOW)))
        run.assert_not_called()

    def test_fetch_source_runs_the_actor_and_marks_the_state(self):
        with tempfile.TemporaryDirectory() as d:
            with mock.patch.dict("os.environ", {"APIFY_TOKEN": "t"}, clear=True), \
                    mock.patch.object(watch, "DATA", Path(d)), quiet(), \
                    mock.patch.object(watch, "apify_run", return_value=b'{"matches": []}') as run:
                self.assertEqual(watch.fetch_source(self.SRC, {}, at(self.NOW)), b'{"matches": []}')
            run.assert_called_once_with(self.SRC, "t")
            state = json.loads((Path(d) / "chatgpt-web.apify-state.json").read_text(encoding="utf-8"))
            self.assertEqual(state["last_run"], self.NOW)

    def test_a_failed_run_still_marks_the_state(self):
        # a failed actor run cost money too; the interval caps retries the same way
        with tempfile.TemporaryDirectory() as d:
            with mock.patch.dict("os.environ", {"APIFY_TOKEN": "t"}, clear=True), \
                    mock.patch.object(watch, "DATA", Path(d)), quiet(), \
                    mock.patch.object(watch, "apify_run",
                                      side_effect=watch.urllib.error.URLError("payment required")):
                with self.assertRaises(watch.urllib.error.URLError):
                    watch.fetch_source(self.SRC, {}, at(self.NOW))
                self.assertFalse(watch.apify_due(self.SRC, at("2026-09-25T13:00Z")))

    def test_plain_sources_go_through_fetch(self):
        with mock.patch.object(watch, "fetch", return_value=b"{}") as f:
            out = watch.fetch_source({"name": "x", "url": "https://x"}, {"A": "b"}, at(self.NOW))
        self.assertEqual(out, b"{}")
        f.assert_called_once_with("https://x", {"A": "b"})

    def test_apify_patterns_are_js_regexes(self):
        # the page function compiles them with new RegExp(pattern, 'gi'): inline flag groups like (?i) break
        # that, while (?:...), (?=...) and (?!...) are fine
        import re
        for src in json.loads(watch.SOURCES.read_text(encoding="utf-8")):
            if src.get("kind") == "apify":
                with self.subTest(source=src["name"]):
                    self.assertIsNone(re.search(r"\(\?[a-z]", src["pattern"]))

    def test_http_error_carries_apifys_message(self):
        err = watch.urllib.error.HTTPError("https://api.apify.com/x", 400, "Bad Request", {},
                                           io.BytesIO(b'{"error":{"message":"bad input"}}'))
        with mock.patch.object(watch.urllib.request, "urlopen", side_effect=err), quiet():
            with self.assertRaises(ValueError) as ctx:
                watch.apify_run(self.SRC, "t")
        self.assertIn("bad input", str(ctx.exception))


class TestWebSourcePatterns(unittest.TestCase):
    """The real chatgpt-web/claude-web patterns against strings the first chatgpt.com snapshot brought."""

    def matches(self, name, text):
        src = next(s for s in json.loads(watch.SOURCES.read_text(encoding="utf-8")) if s["name"] == name)
        # the actor's RegExp runs with the i flag while extract_ids compiles without flags,
        # so feed the text already lowercased — same matches for these patterns
        return watch.extract_ids(text.lower().encode("utf-8"),
                                 {**src, "kind": "text", "extract": "regex"})[1]

    def test_chatgpt_web_keeps_models_and_drops_ui_noise(self):
        ids = self.matches("chatgpt-web",
                           "GPT-5.2.instant.access gpt-6-sol GPT-Live-1 o4-mini GPT-4. "
                           "chatgpt-dv4fkqfn.js codex-canva codex-chatgpt-version-imoe7dyk.js")
        self.assertEqual(ids, ["gpt-4", "gpt-5.2.instant.access", "gpt-6-sol", "gpt-live-1", "o4-mini"])

    def test_chatgpt_web_catches_plan_rollout_strings(self):
        # how a new plan shows up in the bundle: subscription UI strings and planType comparisons —
        # promax surfaced in chatgpt.com's code two hours before PlanType.ts
        ids = self.matches("chatgpt-web",
                           'chatgpt-subscription-complete-pro-max chatgpt-promax-intent-to-pay '
                           'planType:"promax" plan_type="go" "plans.prolite" '
                           '"chatgpt-free-plan" plans are great plan.id')
        self.assertEqual(ids, ["chatgpt-free-plan", "chatgpt-promax-intent-to-pay",
                               "chatgpt-subscription-complete-pro-max", "go", "id", "prolite", "promax"])

    def test_claude_web_keeps_model_ids_and_drops_assets(self):
        ids = self.matches("claude-web",
                           'claude-opus-5-5 claude_wafer_eap Claude-Haiku-4-5 claude.ai claude-app '
                           'claude-main-a1b2c3.js claude-icon.webp planType:"ultra"')
        self.assertEqual(ids, ["claude-app", "claude-haiku-4-5", "claude-opus-5-5", "claude_wafer_eap", "ultra"])

    def test_regex_extract_takes_the_first_matched_group(self):
        # a multi-group pattern used to put None into the id list for matches outside group 1
        src = {"kind": "text", "extract": "regex", "pattern": r"(?:foo-(\w+)|bar-(\w+))"}
        self.assertEqual(watch.extract_ids(b"foo-one bar-two", src)[1], ["one", "two"])

    def test_exclude_drops_asset_filenames(self):
        src = {"kind": "text", "extract": "regex", "pattern": r"\b(gpt-[\w.\-]+)", "exclude": r"\.js$"}
        self.assertEqual(watch.extract_ids(b"gpt-5 gpt-chunk-a1b2.js", src)[1], ["gpt-5"])


class TestSummarize(unittest.TestCase):
    def test_picks_price_and_context(self):
        entry = {"cost": {"input": 2.5, "output": 10}, "limit": {"context": 400000}, "name": "GPT-6 Sol"}
        out = watch.summarize(entry)
        self.assertIn("cost.input=2.5", out)
        self.assertIn("limit.context=400000", out)
        self.assertNotIn("name=", out)

    def test_picks_litellm_field_names(self):
        entry = {"input_cost_per_token": 2.5e-06, "max_input_tokens": 400000, "litellm_provider": "openai"}
        out = watch.summarize(entry)
        self.assertIn("input_cost_per_token=2.5e-06", out)
        self.assertIn("max_input_tokens=400000", out)

    def test_truncates_to_budget(self):
        entry = {f"cost_{i}": i for i in range(100)}
        out = watch.summarize(entry, budget=80)
        self.assertLessEqual(len(out), 80)

    def test_cache_fields_go_last(self):
        entry = {
            "cache_read_input_token_cost": 1.5e-06,
            "input_cost_per_token": 1.5e-05,
            "output_cost_per_token": 7.5e-05,
        }
        out = watch.summarize(entry)
        self.assertLess(out.index("input_cost_per_token="), out.index("cache_read_input_token_cost="))
        self.assertLess(out.index("output_cost_per_token="), out.index("cache_read_input_token_cost="))

    def test_entry_without_interesting_fields(self):
        self.assertEqual(watch.summarize({"name": "x", "owner": "y"}), "")

    def test_non_dict_entry(self):
        self.assertEqual(watch.summarize(None), "")
        self.assertEqual(watch.summarize("gpt-6-sol"), "")


class TestFormatChange(unittest.TestCase):
    def test_added_id_carries_details(self):
        parsed = {"gpt-6-sol": {"input_cost_per_token": 2.5e-06, "max_input_tokens": 400000}}
        src = {"name": "litellm-prices", "url": "https://example/x.json", "extract": "top_keys"}
        out = watch.format_change(src, ["gpt-6-sol"], [], parsed)
        self.assertIn("• litellm-prices", out)
        self.assertIn("+ gpt-6-sol", out)
        self.assertIn("max_input_tokens=400000", out)

    def test_removed_id_stays_plain(self):
        src = {"name": "openrouter", "url": "https://example/y"}
        out = watch.format_change(src, [], ["old-model"], None)
        self.assertIn("− old-model", out)
        self.assertNotIn("+", out.split("\n", 1)[1])

    def test_details_only_for_first_few(self):
        parsed = {f"gpt-{i}": {"max_input_tokens": 1000 + i} for i in range(watch.DETAIL_LIMIT + 3)}
        src = {"name": "n", "url": "u", "extract": "top_keys"}
        out = watch.format_change(src, sorted(parsed), [], parsed)
        self.assertEqual(out.count("max_input_tokens="), watch.DETAIL_LIMIT)

    def test_unknown_id_degrades_to_bare_line(self):
        src = {"name": "n", "url": "u", "extract": "top_keys"}
        out = watch.format_change(src, ["ghost"], [], {})
        self.assertIn("+ ghost", out)

    def test_novel_id_is_marked(self):
        src = {"name": "openrouter", "url": "u"}
        out = watch.format_change(src, ["openai/gpt-6-sol", "openai/gpt-5"], [], None, novel={"openai/gpt-6-sol"})
        self.assertIn("+ openai/gpt-6-sol 🆕", out)
        self.assertNotIn("gpt-5 🆕", out)

    def test_long_removal_list_is_collapsed(self):
        src = {"name": "litellm-prices", "url": "u"}
        removed = [f"old-{i:03d}" for i in range(watch.REMOVED_LIMIT + 136)]
        out = watch.format_change(src, [], removed, None)
        self.assertEqual(out.count("− old-"), watch.REMOVED_LIMIT)
        self.assertIn("… ещё 136", out)


class TestBaseName(unittest.TestCase):
    CASES = {
        "azureml://registries/azure-openai/models/gpt-6-sol": "gpt-6-sol",
        "azureml://registries/azureml-xai/models/grok-4-1-fast-reasoning/versions/3": "grok-4-1-fast-reasoning",
        "openai/gpt-6-sol-pro:batch": "gpt-6-sol-pro",
        "openrouter/sonoma-dusk-alpha": "sonoma-dusk-alpha",
        "anthropic/claude-opus-5.5": "claude-opus-5-5",
        "claude-opus-5-5": "claude-opus-5-5",
        "claude-haiku-4-5@20251001": "claude-haiku-4-5",
        "gpt-6-sol@eu": "gpt-6-sol",
        "us.anthropic.claude-opus-5-5": "claude-opus-5-5",
        "global.openai.gpt-6-luna": "gpt-6-luna",
        "bedrock/us-gov-east-1/anthropic.claude-opus-5-5": "claude-opus-5-5",
        "anthropic.claude-3-7-sonnet-20250219-v1:0": "claude-3-7-sonnet",
        "bedrock/us-west-2/1-month-commitment/anthropic.claude-v2:1": "claude-v2",
        "azure/gpt-5.4-pro-2026-03-05": "gpt-5-4-pro",
        "azure/us/gpt-5-nano-2025-08-07": "gpt-5-nano",
        "xai/grok-code-fast-1-0825": "grok-code-fast-1",
        "vertex_ai/gemini-2.0-flash": "gemini-2-0-flash",
        "@cf/openai/gpt-oss-120b": "gpt-oss-120b",
        "GPT-5.5": "gpt-5-5",
        "1024-x-1024/gpt-image-1.5": "gpt-image-1-5",
    }

    def test_real_ids_reduce_to_comparable_names(self):
        for raw, expected in self.CASES.items():
            with self.subTest(raw=raw):
                self.assertEqual(watch.base_name(raw), expected)


class TestIsKnown(unittest.TestCase):
    def test_exact_match(self):
        self.assertTrue(watch.is_known("gpt-6-sol", {"gpt-6-sol"}))

    def test_provider_prefixed_variant_of_known_model(self):
        self.assertTrue(watch.is_known("databricks-gemini-2-5-flash", {"gemini-2-5-flash"}))
        self.assertTrue(watch.is_known("anthropic-claude-opus-4-8", {"claude-opus-4-8"}))

    def test_new_tier_of_known_model_is_new(self):
        self.assertFalse(watch.is_known("gpt-6-sol-pro", {"gpt-6-sol"}))

    def test_single_token_names_do_not_match_as_suffix(self):
        self.assertFalse(watch.is_known("codex-o3", {"o3"}))

    def test_unseen_name(self):
        self.assertFalse(watch.is_known("gpt-6-astra", {"gpt-6-sol", "gpt-6-luna"}))

    def test_serving_mode_of_known_model_is_known(self):
        self.assertTrue(watch.is_known("gpt-6-sol-fast", {"gpt-6-sol"}))
        self.assertTrue(watch.is_known("claude-opus-5-5-thinking", {"claude-opus-5-5"}))

    def test_serving_mode_of_unseen_model_is_new(self):
        self.assertFalse(watch.is_known("claude-opus-6-fast", {"claude-opus-5-5"}))

    def test_unversioned_alias_of_known_model_is_known(self):
        self.assertTrue(watch.is_known("grok-code-fast", {"grok-code-fast-1"}))

    def test_family_name_is_not_an_alias_of_a_named_model(self):
        self.assertFalse(watch.is_known("gpt-6", {"gpt-6-sol", "gpt-6-luna"}))


class TestLoadKnown(unittest.TestCase):
    def test_reads_every_ids_file(self):
        with tempfile.TemporaryDirectory() as d:
            Path(d, "openrouter.ids.txt").write_text("openai/gpt-5\nanthropic/claude-opus-5.5\n", encoding="utf-8")
            Path(d, "litellm-prices.ids.txt").write_text("azure/us/gpt-5-nano-2025-08-07\n", encoding="utf-8")
            Path(d, "openrouter.json").write_text("{}", encoding="utf-8")
            self.assertEqual(watch.load_known(Path(d)), {"gpt-5", "claude-opus-5-5", "gpt-5-nano"})

    def test_missing_dir_means_nothing_known(self):
        self.assertEqual(watch.load_known(Path("/nonexistent/model-watch-data")), set())


def at(stamp):
    return watch.datetime.strptime(stamp, watch.TIME_FORMAT).replace(tzinfo=watch.timezone.utc)


class TestSeenMemory(unittest.TestCase):
    def test_a_missing_file_is_an_empty_memory(self):
        with tempfile.TemporaryDirectory() as d:
            self.assertEqual(watch.load_seen(Path(d)), {})

    def test_round_trip(self):
        seen = {"gpt-6-sol": {"first_seen": "2026-09-22T13:10Z", "catalog": True, "pulled": "2026-09-22T15:27Z"},
                "codex-rs": {"first_seen": "", "catalog": False, "pulled": ""}}
        with tempfile.TemporaryDirectory() as d:
            watch.save_seen(Path(d), seen)
            self.assertEqual(watch.load_seen(Path(d)), seen)
            self.assertNotIn("\t\n", (Path(d) / watch.SEEN_FILE).read_text(encoding="utf-8"))

    def test_new_names_get_the_time_and_catalog_flag(self):
        seen = {}
        snapshot = {"azure": {"gpt-6-sol"}, "feed": {"gpt-6-sol", "codex-rs"}}
        watch.remember(seen, snapshot, {"azure"}, at("2026-09-22T13:10Z"))
        self.assertEqual(seen["gpt-6-sol"], {"first_seen": "2026-09-22T13:10Z", "catalog": True, "pulled": ""})
        self.assertEqual(seen["codex-rs"], {"first_seen": "2026-09-22T13:10Z", "catalog": False, "pulled": ""})

    def test_names_from_a_newly_connected_source_have_no_time(self):
        seen = {}
        watch.remember(seen, {"anthropic-api": {"claude-opus-5"}}, {"anthropic-api"}, at("2026-09-22T13:10Z"),
                       untimed_sources={"anthropic-api"})
        self.assertEqual(seen["claude-opus-5"]["first_seen"], "")

    def test_a_timed_source_wins_over_a_new_one(self):
        seen = {}
        watch.remember(seen, {"new": {"gpt-6-sol"}, "azure": {"gpt-6-sol"}}, {"new", "azure"},
                       at("2026-09-22T13:10Z"), untimed_sources={"new"})
        self.assertEqual(seen["gpt-6-sol"]["first_seen"], "2026-09-22T13:10Z")

    def test_first_seen_is_never_overwritten_and_catalog_only_turns_on(self):
        seen = {"gpt-6-sol": {"first_seen": "2026-09-21T08:00Z", "catalog": False, "pulled": ""}}
        watch.remember(seen, {"azure": {"gpt-6-sol"}}, {"azure"}, at("2026-09-22T13:10Z"))
        self.assertEqual(seen["gpt-6-sol"], {"first_seen": "2026-09-21T08:00Z", "catalog": True, "pulled": ""})
        watch.remember(seen, {"feed": {"gpt-6-sol"}}, {"azure"}, at("2026-09-23T13:10Z"))
        self.assertTrue(seen["gpt-6-sol"]["catalog"])


class TestCatalogEvents(unittest.TestCase):
    CATALOGS = {"azure", "openrouter"}
    NOW = at("2026-09-22T18:59Z")

    def test_a_pulled_name_back_in_a_catalog_has_returned(self):
        seen = {"gpt-6-sol": {"first_seen": "2026-09-22T13:10Z", "catalog": True, "pulled": "2026-09-22T15:27Z"}}
        returned, pulled = watch.catalog_events(
            {"azure": set(), "openrouter": set()}, {"azure": {"gpt-6-sol"}, "openrouter": {"gpt-6-sol"}},
            self.CATALOGS, seen, self.NOW)
        self.assertEqual(returned, [{"name": "gpt-6-sol", "sources": ["azure", "openrouter"]}])
        self.assertEqual(pulled, [])

    def test_an_old_name_coming_back_is_not_an_event(self):
        # litellm dropped grok-3-beta in a cleanup on 22.09; a revert would bring it back
        seen = {"grok-3-beta": {"first_seen": "", "catalog": True, "pulled": ""}}
        returned, _ = watch.catalog_events({"azure": set()}, {"azure": {"grok-3-beta"}}, self.CATALOGS, seen, self.NOW)
        self.assertEqual(returned, [])

    def test_note_events_marks_pulled_names_and_clears_returned_ones(self):
        seen = {"gpt-6-astra-minor": {"first_seen": "2026-09-22T13:10Z", "catalog": True, "pulled": ""},
                "gpt-6-sol": {"first_seen": "2026-09-22T13:10Z", "catalog": True, "pulled": "2026-09-22T15:27Z"}}
        watch.note_events(seen, [{"name": "gpt-6-sol"}], [{"name": "gpt-6-astra-minor"}], self.NOW)
        self.assertEqual(seen["gpt-6-astra-minor"]["pulled"], "2026-09-22T18:59Z")
        self.assertEqual(seen["gpt-6-sol"]["pulled"], "")

    def test_a_newly_connected_source_brings_nothing_back(self):
        seen = {"claude-opus-5": {"first_seen": "", "catalog": True, "pulled": "2026-09-20T10:00Z"}}
        returned, _ = watch.catalog_events({"azure": set()}, {"azure": set(), "openrouter": {"claude-opus-5"}},
                                           self.CATALOGS, seen, self.NOW, new_sources={"openrouter"})
        self.assertEqual(returned, [])

    def test_a_fresh_name_gone_from_every_catalog_was_pulled(self):
        seen = {"gpt-6-astra-minor": {"first_seen": "2026-09-22T13:10Z", "catalog": True}}
        _, pulled = watch.catalog_events({"azure": {"gpt-5", "gpt-6-astra-minor"}}, {"azure": {"gpt-5"}},
                                         self.CATALOGS, seen, at("2026-09-22T15:27Z"))
        self.assertEqual(pulled, [{"name": "gpt-6-astra-minor", "since": "2026-09-22T13:10Z", "sources": ["azure"],
                                   "still": []}])

    def test_a_fresh_name_leaving_one_catalog_was_pulled_from_it(self):
        # litellm and models-dev copy a leaked name within hours and seldom drop it; waiting for every catalog to
        # let go would miss the cleanup in the catalog that matters
        seen = {"gpt-6-sol": {"first_seen": "2026-09-22T13:10Z", "catalog": True, "pulled": ""}}
        _, pulled = watch.catalog_events({"azure": {"gpt-5", "gpt-6-sol"}, "openrouter": {"gpt-6-sol"}},
                                         {"azure": {"gpt-5"}, "openrouter": {"gpt-6-sol"}}, self.CATALOGS, seen,
                                         self.NOW)
        self.assertEqual(pulled, [{"name": "gpt-6-sol", "since": "2026-09-22T13:10Z", "sources": ["azure"],
                                   "still": ["openrouter"]}])

    def test_a_pulled_name_back_in_one_catalog_has_returned_while_another_kept_it(self):
        seen = {"gpt-6-sol": {"first_seen": "2026-09-22T13:10Z", "catalog": True, "pulled": "2026-09-22T15:27Z"}}
        returned, pulled = watch.catalog_events(
            {"azure": {"gpt-5"}, "openrouter": {"gpt-6-sol"}},
            {"azure": {"gpt-5", "gpt-6-sol"}, "openrouter": {"gpt-6-sol"}}, self.CATALOGS, seen, self.NOW)
        self.assertEqual(returned, [{"name": "gpt-6-sol", "sources": ["azure"]}])
        self.assertEqual(pulled, [])

    def test_a_variant_of_a_name_still_listed_was_not_pulled(self):
        # a catalog renaming its copy (openai-gpt-6-sol → gpt-6-sol) or dropping a serving mode is not a cleanup
        seen = {"openai-gpt-6-sol": {"first_seen": "2026-09-22T21:59Z", "catalog": True, "pulled": ""},
                "gpt-6-sol-fast": {"first_seen": "2026-09-22T21:59Z", "catalog": True, "pulled": ""}}
        _, pulled = watch.catalog_events({"azure": {"gpt-5", "openai-gpt-6-sol", "gpt-6-sol-fast"}},
                                         {"azure": {"gpt-5", "gpt-6-sol"}}, self.CATALOGS, seen, self.NOW)
        self.assertEqual(pulled, [])

    def test_a_catalog_that_looks_broken_raises_no_pulls(self):
        seen = {"gpt-6-sol": {"first_seen": "2026-09-22T13:10Z", "catalog": True, "pulled": ""}}
        long_list = {f"model-{i:02}" for i in range(20)}
        with quiet():
            _, emptied = watch.catalog_events({"azure": {"gpt-5", "gpt-6-sol"}}, {"azure": set()},
                                              self.CATALOGS, seen, self.NOW)
            _, halved = watch.catalog_events({"azure": long_list | {"gpt-6-sol"}}, {"azure": set(sorted(long_list)[:9])},
                                             self.CATALOGS, seen, self.NOW)
        self.assertEqual((emptied, halved), ([], []))

    def test_old_names_leaving_are_routine_cleanup(self):
        seen = {"gpt-3-5-turbo": {"first_seen": "", "catalog": True},
                "gpt-5-1-chat": {"first_seen": "2026-09-01T10:00Z", "catalog": True}}
        _, pulled = watch.catalog_events({"azure": {"gpt-5", "gpt-3-5-turbo", "gpt-5-1-chat"}}, {"azure": {"gpt-5"}},
                                         self.CATALOGS, seen, self.NOW)
        self.assertEqual(pulled, [])

    def test_commit_feeds_are_not_catalogs(self):
        seen = {"codex-rs": {"first_seen": "2026-09-22T13:10Z", "catalog": False}}
        returned, pulled = watch.catalog_events({"feed": {"codex-rs"}}, {"feed": set()},
                                                self.CATALOGS, seen, self.NOW)
        self.assertEqual((returned, pulled), ([], []))


class TestLooksBroken(unittest.TestCase):
    TWENTY = {f"model-{i:02}" for i in range(20)}

    def test_an_emptied_catalog_looks_broken(self):
        self.assertTrue(watch.looks_broken({"gpt-5", "gpt-6-sol"}, set()))

    def test_a_long_list_that_lost_more_than_half_looks_broken(self):
        self.assertTrue(watch.looks_broken(self.TWENTY, set(sorted(self.TWENTY)[:9])))
        self.assertFalse(watch.looks_broken(self.TWENTY, set(sorted(self.TWENTY)[:10])))

    def test_a_short_list_may_really_lose_most_of_it(self):
        self.assertFalse(watch.looks_broken({"gpt-5", "gpt-6-sol", "gpt-6-astra-minor"}, {"gpt-5"}))

    def test_a_catalog_that_never_listed_anything_is_fine(self):
        self.assertFalse(watch.looks_broken(set(), set()))


def change(name, added, removed=(), parsed=None, extract="key", is_new=False, novel=(), count=None):
    src = {"name": name, "url": f"https://example/{name}", "extract": extract}
    return {"src": src, "added": list(added), "removed": list(removed), "parsed": parsed,
            "is_new": is_new, "novel": set(novel), "count": count if count is not None else len(added)}


class TestGroupNovel(unittest.TestCase):
    def test_same_model_across_sources_is_grouped(self):
        changes = [
            change("azure-foundry-playground", ["azureml://registries/azure-openai/models/gpt-6-sol"],
                   extract="regex", novel={"azureml://registries/azure-openai/models/gpt-6-sol"}),
            change("litellm-prices", ["gpt-6-sol", "azure/gpt-5"], extract="top_keys",
                   parsed={"gpt-6-sol": {"max_input_tokens": 1000000}, "azure/gpt-5": {}}, novel={"gpt-6-sol"}),
        ]
        groups = watch.group_novel(changes)
        self.assertEqual(list(groups), ["gpt-6-sol"])
        self.assertEqual([a["source"] for a in groups["gpt-6-sol"]], ["azure-foundry-playground", "litellm-prices"])
        self.assertEqual(groups["gpt-6-sol"][1]["details"], "max_input_tokens=1000000")

    def test_first_snapshot_is_not_novel(self):
        changes = [change("anthropic-api", [], is_new=True, count=12)]
        self.assertEqual(watch.group_novel(changes), {})


class TestBuildAiPayload(unittest.TestCase):
    def test_orders_by_breadth_and_caps(self):
        groups = {f"model-{i:02d}": [{"source": "feed-openai-codex", "id": f"model-{i:02d}"}]
                  for i in range(watch.AI_NOVEL_LIMIT + 5)}
        groups["gpt-6-sol"] = [{"source": s, "id": "gpt-6-sol"} for s in ("a", "b", "c")]
        payload = watch.build_ai_payload(groups, [])
        self.assertEqual(payload["novel"][0]["name"], "gpt-6-sol")
        self.assertEqual(payload["novel"][0]["sources"], ["a", "b", "c"])
        self.assertEqual(len(payload["novel"]), watch.AI_NOVEL_LIMIT)
        self.assertEqual(payload["more_novel"], 6)

    def test_caps_appearances_per_model(self):
        groups = {"claude-opus-5-5": [{"source": "models-dev", "id": f"v{i}"} for i in range(watch.AI_SEEN_IN_LIMIT + 5)]}
        entry = watch.build_ai_payload(groups, [])["novel"][0]
        self.assertEqual(len(entry["seen_in"]), watch.AI_SEEN_IN_LIMIT)
        self.assertEqual(entry["more_appearances"], 5)

    def test_other_changes_summarise_known_additions_and_removals(self):
        changes = [
            change("litellm-prices", ["azure/gpt-5", "gpt-6-sol"], removed=[f"old-{i}" for i in range(146)],
                   novel={"gpt-6-sol"}),
            change("anthropic-api", [], is_new=True, count=12),
            change("openrouter", []),
        ]
        other = {o["source"]: o for o in watch.build_ai_payload({}, changes)["other_changes"]}
        self.assertEqual(other["litellm-prices"]["added_known"], 1)
        self.assertEqual(other["litellm-prices"]["removed"], 146)
        self.assertEqual(other["litellm-prices"]["examples_added"], ["azure/gpt-5"])
        self.assertEqual(len(other["litellm-prices"]["examples_removed"]), 3)
        self.assertEqual(other["anthropic-api"], {"source": "anthropic-api", "first_snapshot": True, "ids": 12})
        self.assertNotIn("openrouter", other)


class FakeMessages:
    def __init__(self, response=None, error=None):
        self.calls, self.response, self.error = [], response, error

    def create(self, **kwargs):
        self.calls.append(kwargs)
        if self.error:
            raise self.error
        return self.response


def fake_client(**kwargs):
    return SimpleNamespace(messages=FakeMessages(**kwargs))


def fake_response(text="Похоже на релиз GPT-6.", stop_reason="end_turn", model="xiaomi/mimo-v2.6-flash"):
    return SimpleNamespace(
        content=[SimpleNamespace(type="thinking", thinking=""), SimpleNamespace(type="text", text=text)],
        stop_reason=stop_reason, stop_details=None, model=model,
        usage=SimpleNamespace(input_tokens=1200, output_tokens=300),
    )


class TestGithubOidcToken(unittest.TestCase):
    ENV = {"ACTIONS_ID_TOKEN_REQUEST_URL": "https://gh.example/token?api-version=2.0",
           "ACTIONS_ID_TOKEN_REQUEST_TOKEN": "runner-secret"}

    def test_none_outside_github_actions(self):
        with mock.patch.dict("os.environ", {}, clear=True), mock.patch.object(watch.urllib.request, "urlopen") as urlopen:
            self.assertIsNone(watch.github_oidc_token("model-watch-ai"))
        urlopen.assert_not_called()

    def test_requests_a_token_for_the_audience(self):
        reply = mock.MagicMock()
        reply.__enter__.return_value.read.return_value = b'{"value": "github-jwt"}'
        with mock.patch.dict("os.environ", self.ENV, clear=True), \
                mock.patch.object(watch.urllib.request, "urlopen", return_value=reply) as urlopen:
            self.assertEqual(watch.github_oidc_token("model-watch-ai"), "github-jwt")
        request = urlopen.call_args[0][0]
        self.assertEqual(request.full_url, "https://gh.example/token?api-version=2.0&audience=model-watch-ai")
        self.assertEqual(request.get_header("Authorization"), "bearer runner-secret")

    def test_failure_is_no_token(self):
        with mock.patch.dict("os.environ", self.ENV, clear=True), quiet(), \
                mock.patch.object(watch.urllib.request, "urlopen", side_effect=watch.urllib.error.URLError("down")):
            self.assertIsNone(watch.github_oidc_token("model-watch-ai"))


class TestAiSummary(unittest.TestCase):
    PAYLOAD = {"novel": [{"name": "gpt-6-sol", "sources": ["litellm-prices"], "seen_in": []}], "more_novel": 0,
               "other_changes": []}

    def test_off_without_a_proxy(self):
        with mock.patch.dict("os.environ", {}, clear=True), quiet():
            self.assertIsNone(watch.ai_summary(self.PAYLOAD))

    def test_off_without_a_github_token(self):
        with mock.patch.dict("os.environ", {"AI_PROXY_URL": "https://proxy.example/api"}, clear=True), quiet():
            self.assertIsNone(watch.ai_summary(self.PAYLOAD))

    def test_talks_to_the_proxy_with_the_github_token(self):
        made = []

        def make_client(**kwargs):
            made.append(kwargs)
            return fake_client(response=fake_response())

        sdk = SimpleNamespace(Anthropic=make_client, APIStatusError=RuntimeError)
        with mock.patch.dict("os.environ", {"AI_PROXY_URL": "https://proxy.example/api"}, clear=True), \
                mock.patch.object(watch, "github_oidc_token", return_value="github-jwt") as token, \
                mock.patch.object(watch, "anthropic", sdk), quiet():
            self.assertEqual(watch.ai_summary(self.PAYLOAD), "Похоже на релиз GPT-6.")
        token.assert_called_once_with(watch.AI_AUDIENCE)
        self.assertEqual(made[0]["api_key"], "github-jwt")
        self.assertEqual(made[0]["base_url"], "https://proxy.example/api")

    def test_request_shape(self):
        client = fake_client(response=fake_response())
        with quiet():
            watch.ai_summary(self.PAYLOAD, client=client)
        call = client.messages.calls[0]
        self.assertEqual(call["model"], "xiaomi/mimo-v2.6-flash")
        for claude_only in ("betas", "fallbacks", "output_config"):
            self.assertNotIn(claude_only, call)
        self.assertEqual(call["max_tokens"], watch.AI_MAX_TOKENS)
        self.assertEqual(call["system"], watch.AI_SYSTEM_PROMPT)
        self.assertEqual(call["messages"][0]["role"], "user")
        sent = call["messages"][0]["content"]
        self.assertEqual(json.loads(sent[sent.index("{"):]), self.PAYLOAD)

    def test_returns_text_blocks_only(self):
        client = fake_client(response=fake_response(text="  Похоже на релиз GPT-6.  "))
        with quiet():
            self.assertEqual(watch.ai_summary(self.PAYLOAD, client=client), "Похоже на релиз GPT-6.")

    def test_refusal_falls_back_to_plain_report(self):
        client = fake_client(response=fake_response(text="", stop_reason="refusal"))
        with quiet():
            self.assertIsNone(watch.ai_summary(self.PAYLOAD, client=client))

    def test_api_error_never_raises(self):
        client = fake_client(error=RuntimeError("boom"))
        with quiet():
            self.assertIsNone(watch.ai_summary(self.PAYLOAD, client=client))

    def test_empty_text_is_no_summary(self):
        client = fake_client(response=fake_response(text="   "))
        with quiet():
            self.assertIsNone(watch.ai_summary(self.PAYLOAD, client=client))

    def test_logs_tokens_and_cost(self):
        client = fake_client(response=fake_response())
        out = io.StringIO()
        with contextlib.redirect_stdout(out):
            watch.ai_summary(self.PAYLOAD, client=client)
        self.assertIn("input=1200 output=300", out.getvalue())
        self.assertIn("$0.000252", out.getvalue())  # 1200 * $0.14/M + 300 * $0.28/M

    def test_prices_a_bare_model_name_too(self):
        client = fake_client(response=fake_response(model="mimo-v2.6-flash"))
        out = io.StringIO()
        with contextlib.redirect_stdout(out):
            watch.ai_summary(self.PAYLOAD, client=client)
        self.assertIn("$0.000252", out.getvalue())


class TestFormatMessage(unittest.TestCase):
    BLOCKS = ["• litellm-prices (u)\n  + gpt-6-sol 🆕"]

    def test_novel_with_summary_is_news_and_leads_with_it(self):
        text, news = watch.format_message(self.BLOCKS, ["gpt-6-sol"], "Похоже на релиз GPT-6.")
        self.assertTrue(news)
        self.assertTrue(text.startswith("model-watch: 🆕"))
        self.assertLess(text.index("Похоже на релиз"), text.index("• litellm-prices"))

    def test_novel_without_summary_names_the_models(self):
        text, news = watch.format_message(self.BLOCKS, ["gpt-6-luna", "gpt-6-sol"], None)
        self.assertTrue(news)
        self.assertIn("gpt-6-luna, gpt-6-sol", text.split("\n", 1)[0])

    def test_nothing_novel_is_not_news(self):
        text, news = watch.format_message(["• litellm-prices (u)\n  + azure/gpt-5"], [], None)
        self.assertFalse(news)
        self.assertIn("новых моделей нет", text.split("\n", 1)[0])

    RETURNED = [{"name": "gpt-6-sol", "sources": ["azure-foundry-playground", "openrouter"]}]
    PULLED = [{"name": "gpt-6-astra-minor", "since": "2026-09-22T13:10Z", "sources": ["azure-foundry-playground"],
               "still": []}]

    def test_a_return_is_news(self):
        text, news = watch.format_message(["• azure (u)\n  + gpt-6-sol"], [], None, returned=self.RETURNED)
        self.assertTrue(news)
        self.assertIn("↩️", text.split("\n", 1)[0])
        self.assertIn("↩️ вернулось: gpt-6-sol — снова в azure-foundry-playground, openrouter", text)

    def test_a_pulled_leak_is_news_and_says_when_it_appeared(self):
        text, news = watch.format_message(["• azure (u)\n  − gpt-6-astra-minor"], [], None, pulled=self.PULLED)
        self.assertTrue(news)
        self.assertIn("🫥", text.split("\n", 1)[0])
        self.assertIn("🫥 убрали: gpt-6-astra-minor из azure-foundry-playground — появилось 22.09 13:10 UTC, "
                      "больше ни в одном каталоге", text)

    def test_a_pull_says_which_catalogs_still_list_the_name(self):
        pulled = [{"name": "gpt-6-sol", "since": "2026-09-22T18:59Z", "sources": ["azure-foundry-playground"],
                   "still": ["litellm-prices", "models-dev"]}]
        text, _ = watch.format_message(["• azure (u)\n  − gpt-6-sol"], [], None, pulled=pulled)
        self.assertIn("🫥 убрали: gpt-6-sol из azure-foundry-playground — появилось 22.09 18:59 UTC, "
                      "ещё есть в litellm-prices, models-dev", text)

    def test_events_come_before_the_ai_summary_and_the_diff(self):
        text, _ = watch.format_message(self.BLOCKS, ["gpt-6-sol"], "Похоже на релиз GPT-6.", pulled=self.PULLED)
        self.assertTrue(text.startswith("model-watch: 🆕"))
        self.assertLess(text.index("🫥 убрали"), text.index("Похоже на релиз"))
        self.assertLess(text.index("Похоже на релиз"), text.index("— — —"))
        self.assertLess(text.index("— — —"), text.index("• litellm-prices"))


class TestSendTelegram(unittest.TestCase):
    def test_every_message_rings(self):
        # only news reaches Telegram now, so nothing is sent without a sound
        with mock.patch.dict("os.environ", {"TELEGRAM_BOT_TOKEN": "t", "TELEGRAM_CHAT_ID": "1"}), \
                mock.patch.object(watch.urllib.request, "urlopen") as urlopen:
            watch.send_telegram("hello")
        payload = json.loads(urlopen.call_args[0][0].data.decode("utf-8"))
        self.assertEqual(payload["text"], "hello")
        self.assertNotIn("disable_notification", payload)


class TestAiSelftest(unittest.TestCase):
    def test_sends_one_summary_of_the_recorded_example(self):
        client = fake_client(response=fake_response(text="Похоже на релиз GPT-6 и Claude Opus 5.5."))
        with quiet(), mock.patch.object(watch, "send_telegram") as send:
            code = watch.run_ai_selftest(client=client)
        self.assertEqual(code, 0)
        payload = json.loads(client.messages.calls[0]["messages"][0]["content"].split("\n", 1)[1])
        names = {n["name"] for n in payload["novel"]}
        self.assertTrue({"gpt-6-sol", "gpt-6-luna", "claude-opus-5-5"} <= names)
        self.assertNotIn("gpt-5-4", names)  # known before the recorded run
        text = send.call_args[0][0]
        self.assertIn("самотест", text.split("\n", 1)[0])
        self.assertIn("Похоже на релиз GPT-6 и Claude Opus 5.5.", text)

    def test_fails_loudly_without_a_summary(self):
        with mock.patch.dict("os.environ", {}, clear=True), quiet(), mock.patch.object(watch, "send_telegram") as send:
            self.assertEqual(watch.run_ai_selftest(), 1)
        send.assert_not_called()


class TestChainWarning(unittest.TestCase):
    NOW = "2026-09-22T15:10Z"

    def warn(self, runs=None, error=None, repo="vova/model-watch"):
        calls = []

        def api(path):
            calls.append(path)
            if error:
                raise error
            return {"workflow_runs": runs or []}

        env = {"GITHUB_REPOSITORY": repo} if repo else {}
        with mock.patch.dict("os.environ", env, clear=True), quiet():
            return watch.chain_warning(at(self.NOW), api=api), calls

    def test_quiet_while_the_chain_runs(self):
        warning, calls = self.warn([{"created_at": "2026-09-22T15:01:40Z"}])
        self.assertIsNone(warning)
        self.assertEqual(calls, ["/repos/vova/model-watch/actions/workflows/watch.yml/runs?event=workflow_dispatch&per_page=1"])

    def test_warns_when_the_chain_stopped(self):
        warning, _ = self.warn([{"created_at": "2026-09-22T13:10:05Z"}])
        self.assertTrue(warning.startswith("⚠️ model-watch: цепочка tick встала."))
        self.assertIn("22.09 13:10 UTC, 119 мин назад", warning)
        self.assertIn("Actions → tick → Run workflow", warning)

    def test_warns_when_the_chain_never_ran(self):
        warning, _ = self.warn([])
        self.assertIn("ещё ни разу", warning)

    def test_silent_when_github_cannot_tell(self):
        warning, _ = self.warn(error=watch.urllib.error.URLError("timeout"))
        self.assertIsNone(warning)
        warning, _ = self.warn([{"created_at": "вчера"}])
        self.assertIsNone(warning)

    def test_skipped_outside_actions(self):
        warning, calls = self.warn(repo=None)
        self.assertIsNone(warning)
        self.assertEqual(calls, [])

    def test_github_api_sends_the_workflow_token(self):
        response = mock.MagicMock()
        response.__enter__.return_value.read.return_value = b'{"workflow_runs": []}'
        with mock.patch.dict("os.environ", {"GITHUB_TOKEN": "t0k"}, clear=True), \
                mock.patch.object(watch.urllib.request, "urlopen", return_value=response) as urlopen:
            self.assertEqual(watch.github_api("/repos/x/y"), {"workflow_runs": []})
        req = urlopen.call_args[0][0]
        self.assertEqual(req.full_url, "https://api.github.com/repos/x/y")
        self.assertEqual(req.get_header("Authorization"), "Bearer t0k")

    def test_check_chain_flag_sends_the_warning(self):
        with quiet(), mock.patch.object(watch, "chain_warning", return_value="⚠️ встала") as check, \
                mock.patch.object(watch, "send_telegram") as send:
            self.assertEqual(watch.main(["--check-chain"]), 0)
        check.assert_called_once()
        send.assert_called_once_with("⚠️ встала")

    def test_check_chain_flag_stays_quiet_while_the_chain_runs(self):
        with quiet(), mock.patch.object(watch, "chain_warning", return_value=None), \
                mock.patch.object(watch, "send_telegram") as send:
            self.assertEqual(watch.main(["--check-chain"]), 0)
        send.assert_not_called()


class TestMainEndToEnd(unittest.TestCase):
    """Runs main() against a throwaway git repo with file:// sources: the real fetch → diff → message path."""

    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        root = Path(self.tmp.name)
        (root / "data").mkdir()
        self.catalog = root / "catalog.json"
        self.prices = root / "prices.json"
        sources = [
            {"name": "catalog-a", "url": self.catalog.as_uri(), "kind": "json", "extract": "key", "key": "id"},
            {"name": "prices-b", "url": self.prices.as_uri(), "kind": "json", "extract": "top_keys"},
        ]
        (root / "sources.json").write_text(json.dumps(sources), encoding="utf-8")
        (root / "data" / "catalog-a.ids.txt").write_text("gpt-5\n", encoding="utf-8")
        (root / "data" / "prices-b.ids.txt").write_text("claude-opus-4-8\n", encoding="utf-8")
        for args in (["init", "-q"], ["add", "-A"],
                     ["-c", "user.name=t", "-c", "user.email=t@t", "commit", "-q", "-m", "base"]):
            subprocess.run(["git", *args], cwd=root, check=True)
        self.patches = [mock.patch.object(watch, "ROOT", root), mock.patch.object(watch, "DATA", root / "data"),
                        mock.patch.object(watch, "SOURCES", root / "sources.json")]
        for p in self.patches:
            p.start()

    def tearDown(self):
        for p in self.patches:
            p.stop()
        self.tmp.cleanup()

    def run_main(self, catalog, prices):
        self.catalog.write_text(json.dumps(catalog), encoding="utf-8")
        self.prices.write_text(json.dumps(prices), encoding="utf-8")
        out = io.StringIO()
        with contextlib.redirect_stdout(out), contextlib.redirect_stderr(io.StringIO()), \
                mock.patch.object(watch, "send_telegram") as send, \
                mock.patch.object(watch, "ai_summary", return_value="Похоже на релиз GPT-6.") as ai:
            watch.main([])
        self.log = out.getvalue()
        return send, ai

    def test_new_model_gets_an_ai_summary_and_an_alert(self):
        send, ai = self.run_main(
            {"data": [{"id": "gpt-5"}, {"id": "gpt-6-sol", "limit": {"context": 1000000}}]},
            {"claude-opus-4-8": {}, "azure/gpt-5": {"max_input_tokens": 400000}},
        )
        payload = ai.call_args[0][0]
        self.assertEqual([n["name"] for n in payload["novel"]], ["gpt-6-sol"])
        self.assertEqual(payload["novel"][0]["seen_in"][0]["details"], "limit.context=1000000")
        send.assert_called_once()
        text = send.call_args[0][0]
        self.assertTrue(text.startswith("model-watch: 🆕"))
        self.assertIn("Похоже на релиз GPT-6.", text)
        self.assertIn("+ gpt-6-sol 🆕", text)
        self.assertIn("+ azure/gpt-5\n", text + "\n")
        self.assertNotIn("azure/gpt-5 🆕", text)

    def test_known_models_in_new_places_stay_in_the_log(self):
        send, ai = self.run_main(
            {"data": [{"id": "gpt-5"}]},
            {"claude-opus-4-8": {}, "azure/gpt-5": {}, "bedrock/us.anthropic.claude-opus-4-8": {}},
        )
        ai.assert_not_called()
        send.assert_not_called()
        self.assertIn("model-watch: новых моделей нет", self.log)
        self.assertIn("+ azure/gpt-5", self.log)

    def test_no_changes_send_nothing(self):
        send, ai = self.run_main({"data": [{"id": "gpt-5"}]}, {"claude-opus-4-8": {}})
        send.assert_not_called()
        ai.assert_not_called()

    def test_a_regular_check_leaves_the_chain_to_its_own_step(self):
        env = {"GITHUB_EVENT_NAME": "schedule", "GITHUB_REPOSITORY": "vova/model-watch"}
        with mock.patch.dict("os.environ", env), mock.patch.object(watch, "chain_warning") as check:
            self.run_main({"data": [{"id": "gpt-5"}]}, {"claude-opus-4-8": {}})
        check.assert_not_called()


class TestLeakDay(unittest.TestCase):
    """A leak day through main(), shaped like 22.09.2026: a catalog lists two unreleased names, drops both two hours
    later and brings one of them back at launch; the other never returns."""

    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.root = root = Path(self.tmp.name)
        (root / "data").mkdir()
        self.azure = root / "azure.json"
        self.feed = root / "feed.txt"
        sources = [
            {"name": "azure", "url": self.azure.as_uri(), "kind": "json", "extract": "key", "key": "id"},
            {"name": "feed", "url": self.feed.as_uri(), "kind": "text", "extract": "regex",
             "pattern": r"\b((?:gpt|codex)-[\w.\-]+)", "alert_removed": False},
        ]
        (root / "sources.json").write_text(json.dumps(sources), encoding="utf-8")
        (root / "data" / "azure.ids.txt").write_text("gpt-5\n", encoding="utf-8")
        (root / "data" / "feed.ids.txt").write_text("", encoding="utf-8")
        self.git("init", "-q")
        self.commit()
        self.patches = [mock.patch.object(watch, "ROOT", root), mock.patch.object(watch, "DATA", root / "data"),
                        mock.patch.object(watch, "SOURCES", root / "sources.json")]
        for p in self.patches:
            p.start()

    def tearDown(self):
        for p in self.patches:
            p.stop()
        self.tmp.cleanup()

    def git(self, *args):
        subprocess.run(["git", "-c", "user.name=t", "-c", "user.email=t@t", *args], cwd=self.root,
                       check=False, capture_output=True)

    def commit(self):  # what the workflow's "Commit snapshot" step does after every check
        self.git("add", "-A")
        self.git("commit", "-q", "-m", "snapshot")

    def check(self, stamp, azure_ids, feed_text=""):
        self.azure.write_text(json.dumps({"data": [{"id": i} for i in azure_ids]}), encoding="utf-8")
        self.feed.write_text(feed_text, encoding="utf-8")
        with quiet(), mock.patch.object(watch, "utc_now", return_value=at(stamp)), \
                mock.patch.object(watch, "send_telegram") as send, \
                mock.patch.object(watch, "ai_summary", return_value="Похоже на слив GPT-6.") as ai:
            watch.main([])
        self.commit()
        return send, ai

    def test_leak_pulled_then_released(self):
        send, ai = self.check("2026-09-22T13:10Z", ["gpt-5", "gpt-6-sol", "gpt-6-astra-minor"])
        self.assertEqual({n["name"] for n in ai.call_args[0][0]["novel"]}, {"gpt-6-sol", "gpt-6-astra-minor"})
        self.assertTrue(send.call_args[0][0].startswith("model-watch: 🆕"))

        send, ai = self.check("2026-09-22T15:27Z", ["gpt-5"])
        ai.assert_not_called()
        text = send.call_args[0][0]
        send.assert_called_once()
        self.assertTrue(text.startswith("model-watch: 🫥"))
        self.assertIn("🫥 убрали: gpt-6-astra-minor из azure — появилось 22.09 13:10 UTC, больше ни в одном каталоге",
                      text)
        self.assertIn("🫥 убрали: gpt-6-sol из azure — появилось 22.09 13:10 UTC", text)

        send, ai = self.check("2026-09-22T18:59Z", ["gpt-5", "gpt-6-sol"])
        ai.assert_not_called()  # not novel any more: the memory kept it after Azure dropped it
        text = send.call_args[0][0]
        send.assert_called_once()
        self.assertTrue(text.startswith("model-watch: ↩️"))
        self.assertIn("↩️ вернулось: gpt-6-sol — снова в azure", text)
        self.assertNotIn("🆕", text)

        seen = watch.load_seen(self.root / "data")
        self.assertEqual(seen["gpt-6-astra-minor"],  # still waiting to come back
                         {"first_seen": "2026-09-22T13:10Z", "catalog": True, "pulled": "2026-09-22T15:27Z"})
        self.assertEqual(seen["gpt-6-sol"]["pulled"], "")
        self.assertEqual(seen["gpt-5"], {"first_seen": "", "catalog": True, "pulled": ""})  # there before the memory

    def test_a_name_scrolling_back_into_a_commit_feed_is_not_new(self):
        send, _ = self.check("2026-09-22T18:59Z", ["gpt-5"], "bump codex-rs")
        self.assertTrue(send.call_args[0][0].startswith("model-watch: 🆕"))  # first sighting ever is news

        send, _ = self.check("2026-09-23T00:20Z", ["gpt-5"], "docs only")
        send.assert_not_called()  # leaving a rolling feed is not an event

        send, ai = self.check("2026-09-23T12:04Z", ["gpt-5"], "bump codex-rs again")
        ai.assert_not_called()
        send.assert_not_called()  # already known: it stays in the log

    def test_a_model_that_leaves_after_a_week_and_comes_back_is_routine(self):
        self.check("2026-09-22T13:10Z", ["gpt-5", "grok-3-beta"])
        send, _ = self.check("2026-09-30T09:00Z", ["gpt-5"])
        send.assert_not_called()  # a cleanup, not a pulled leak
        send, ai = self.check("2026-10-01T09:00Z", ["gpt-5", "grok-3-beta"])
        ai.assert_not_called()
        send.assert_not_called()  # a revert, not a return

    def test_a_name_a_commit_feed_leaked_is_news_when_a_catalog_lists_it(self):
        self.check("2026-09-22T18:59Z", ["gpt-5"], "route gpt-7 behind a flag")
        self.check("2026-09-23T09:00Z", ["gpt-5"], "docs only")  # the feed scrolled past it
        send, ai = self.check("2026-09-25T18:00Z", ["gpt-5", "gpt-7"], "docs only")
        self.assertEqual([n["name"] for n in ai.call_args[0][0]["novel"]], ["gpt-7"])
        send.assert_called_once()
        self.assertTrue(send.call_args[0][0].startswith("model-watch: 🆕"))

    def test_a_catalog_listing_is_news_while_the_feed_still_mentions_the_name(self):
        self.check("2026-09-22T18:59Z", ["gpt-5"], "route gpt-7 behind a flag")
        send, ai = self.check("2026-09-22T21:59Z", ["gpt-5", "gpt-7"], "route gpt-7 behind a flag")
        self.assertEqual([n["name"] for n in ai.call_args[0][0]["novel"]], ["gpt-7"])
        send.assert_called_once()

    def test_names_the_memory_missed_are_kept_when_they_leave(self):
        # seen.tsv was seeded before the last snapshot, which brought gemini-x; the next check drops it again
        data = self.root / "data"
        watch.save_seen(data, {"gpt-5": {"first_seen": "", "catalog": True, "pulled": ""}})
        (data / "azure.ids.txt").write_text("gemini-x\ngpt-5\n", encoding="utf-8")
        self.commit()
        self.check("2026-09-23T17:00Z", ["gpt-5"])
        self.assertEqual(watch.load_seen(data)["gemini-x"], {"first_seen": "", "catalog": True, "pulled": ""})

    def test_first_check_starts_the_memory_quietly(self):
        send, _ = self.check("2026-09-22T13:10Z", ["gpt-5"])
        send.assert_not_called()
        self.assertEqual(watch.load_seen(self.root / "data"), {"gpt-5": {"first_seen": "", "catalog": True, "pulled": ""}})


if __name__ == "__main__":
    unittest.main()
